Montforttt35/Models/ErrorViewModel.cs
namespace Montforttt35.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Montforttt35/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Montforttt35.Models;
using System.Diagnostics;

namespace Montforttt35.Controllers
{
    public class ClubController : Controller
    {
        private readonly ILogger<ClubController> _logger;

        public ClubController(ILogger<ClubController> logger)
        {
            _logger = logger;
        }

        public IActionResult Presentation()
        {
            return View();
        }
        public IActionResult Organigramme()
        {
            return View();
        }
        public IActionResult Actualites()
        {
            return View();
        }
        public IActionResult Interview()
        {
            return View();
        }
        public IActionResult Progressions()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Montforttt35/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Montforttt35.Models;
using System.Diagnostics;

namespace Montforttt35.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Montforttt35/Views/Club/Actualites.cshtml
@{
    ViewData["Title"] = "Actualités";
}
<h1>@ViewData["Title"]</h1>

Montforttt35/Views/Club/Interview.cshtml
@{
    ViewData["Title"] = "Interview";
}
<h1>@ViewData["Title"]</h1>

Montforttt35/Views/Club/Organigramme.cshtml
@{
    ViewData["Title"] = "Organigramme";
}
<h1>@ViewData["Title"]</h1>

Montforttt35/Views/Club/Presentation.cshtml
@{
    ViewData["Title"] = "Présentation";
}
<h1>@ViewData["Title"]</h1>

Montforttt35/Views/Club/Progressions.cshtml
@{
    ViewData["Title"] = "Progressions";
}
<h1>@ViewData["Title"]</h1>

Montforttt35/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Accueil";
}

<div class="text-center">
    <h1 class="display-4">Montfort Tennis de Table</h1>
    <!-- Messenger Plugin de discussion Code -->

    <div id="fb-root"></div>

    <!-- Your Plugin de discussion code -->
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>

    <script>
        var chatbox = document.getElementById('fb-customer-chat');
        chatbox.setAttribute("page_id", "105083542269903");
        chatbox.setAttribute("attribution", "biz_inbox");
    </script>

    <!-- Your SDK code -->
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                xfbml: true,
                version: 'v14.0'
            });
        };

        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/fr_FR/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</div>

Montforttt35/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>@ViewData["Title"] - Montfort TT 35</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Montforttt35.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white">
            <div class="container-fluid">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="~/logoMontfort.png" style="height: 137.60px;width: 226.40px;" /></a>
                    <h1 class="titre">MONTFORT T.T.</h1>
                </div>
                <div>
                    <a class="btn btn-primary" href="" role="button">Inscription</a>
                    <a class="btn btn-primary" href="" role="button">Connexion</a>
                </div>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
        <nav class="mynavbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="nav">
                        <!--Club-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Le Club &#9662;</a>
                            <ul class="dropdown">
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Presentation">Présentation</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Organigramme">Organigramme</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Actualites">Actualités</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Interview">Interview</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Progressions">Progressions</a>
                                </li>
                            </ul>
                        </li>
                        <!--Infos Pratiques-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Infos Pratiques &#9662;</a>
                            <ul class="dropdown">
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Section loisir</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Section compétiteur</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Entrainements</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Tarifs</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Partenaire</a>
                                </li>
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Liens utiles</a>
                                </li>
                            </ul>
                        </li>
                        <!--Compétitions-->
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Compétitions &#9662;</a>
                            <ul class="dropdown">
                                <li class="nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Championnat par équipe &#9656;</a>
                                    <ul>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Championnat adulte</a></li>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Championnat jeune</a></li>
                                    </ul>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Compétition individuels &#9656;</a>
                                    <ul>
                                        <li>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Critérium &#9656;</a>
                                            <ul>
                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Critérium féminin</a></li>
                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Critérium fédéral</a></li>
                                            </ul>
                                        </li>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Circuit des jeunes</a></li>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Finales par classements</a></li>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Championnat d’Ille-et-Vilaine</a></li>
                                    </ul>
                                </li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Tournois</a></li>
                            </ul>
                        </li>
                        <!--Photos & Vidéos-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Photos & Vidéos</a>
                        </li>
                        <!--Contact & Plan-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Contact & Plan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <p>1</p>
        <p>2</p>
        <p>3</p>
        <p>4</p>
        <p>5</p>
        <p>6</p>
        <p>7</p>
        <p>8</p>
        <p>9</p>
        <p>10</p>
        <p>11</p>
        <p>12</p>
        <p>13</p>
        <p>14</p>
        <p>15</p>
    </div>
    <footer class="footerStyle">
        <div class="containerFooter center">
            <div class="item"><a asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="~/logoMontfort.png" style="height: 137.60px;width: 226.40px;" /></a></div>
            <div class="item"><h1>MONTFORT T.T.</h1></div>
        </div>
        <div class="footerFb">
            <a href="https://www.facebook.com/profile.php?id=100081510012894"><img style="width: 33.60px; height: 34.40px;" src="~/fbIcon.svg" /></a>
        </div>
        <div class="footerRights">
            &copy; 2022 Montfort T.T. - tous droits réservés
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>